# Generated by Django 2.0.2 on 2019-06-30 05:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Bebida')),
                ('descripcion', ckeditor.fields.RichTextField(verbose_name='Descripcion')),
                ('image', models.ImageField(default='', upload_to='productos', verbose_name='Foto')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('stock', models.PositiveIntegerField(verbose_name='Stock')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de ultima modificacion')),
            ],
            options={
                'verbose_name': 'bebida',
                'verbose_name_plural': 'bebidas',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Carrito')),
                ('descripcion', ckeditor.fields.RichTextField(verbose_name='Descripcion')),
                ('image', models.ImageField(default='', upload_to='productos', verbose_name='Foto')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('subtotal', models.FloatField(default=None, verbose_name='Subtotal')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de ultima modificacion')),
            ],
            options={
                'verbose_name': 'carrito',
                'verbose_name_plural': 'carritos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Entrada')),
                ('descripcion', ckeditor.fields.RichTextField(verbose_name='Descripcion')),
                ('image', models.ImageField(default='', upload_to='productos', verbose_name='Foto')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('stock', models.PositiveIntegerField(verbose_name='Stock')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de ultima modificacion')),
            ],
            options={
                'verbose_name': 'entrada',
                'verbose_name_plural': 'entradas',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Plato')),
                ('descripcion', ckeditor.fields.RichTextField(verbose_name='Descripcion')),
                ('image', models.ImageField(default='', upload_to='productos', verbose_name='Foto')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('stock', models.PositiveIntegerField(verbose_name='Stock')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de ultima modificacion')),
            ],
            options={
                'verbose_name': 'plato',
                'verbose_name_plural': 'platos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Promocion')),
                ('descripcion', ckeditor.fields.RichTextField(verbose_name='Descripcion')),
                ('image', models.ImageField(default='', upload_to='productos', verbose_name='Foto')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('stock', models.PositiveIntegerField(verbose_name='Stock')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de ultima modificacion')),
            ],
            options={
                'verbose_name': 'promocion',
                'verbose_name_plural': 'promociones',
                'ordering': ['-created'],
            },
        ),
    ]
