# Generated by Django 2.0.2 on 2019-06-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='address',
            field=models.CharField(default='', max_length=200, verbose_name='address'),
        ),
    ]
