# Generated by Django 2.0.2 on 2019-06-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_myuser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='address'),
        ),
    ]
