# Generated by Django 2.0.2 on 2019-07-01 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190630_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='tarjeta',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='tarjeta'),
        ),
    ]
