# Generated by Django 2.0.2 on 2020-08-28 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190701_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='tarjeta',
        ),
    ]
